spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 5000
      circuitbreaker:
        enabled: true

server:
  error:
    include-message: always
    include-binding-errors: always
