server:
  port: 8081

spring:
  application:
    name: S1-identity-service
  cloud:
    config:
      enabled: false # T?m t?t ?? không b? l?i không tìm th?y Config Server Port 8888
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration # T?m t?t ?? test API không c?n DB